print('Problem nº2: Even Fibonacci Numbers')
print('Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.')

def is_even_number(n):
  return n % 2 == 0

def get_even_terms_of_fibonacci(limit):
  first_term = 0
  second_term = 1
  list_of_even_numbers = []

  while second_term < limit:
    first_term, second_term = second_term, first_term + second_term

    if is_even_number(second_term):
      list_of_even_numbers.append(second_term)

  return list_of_even_numbers

LIMIT = 4000000
print('Solution:', sum(get_even_terms_of_fibonacci(LIMIT)))