pub const TITLE: &str = "Problem nº2: Even Fibonacci Numbers";
pub const DESCRIPTION: &str = "Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";

pub fn solve() -> i32 {
  const LIMIT: i32 = 4_000_000;

  let mut previous_fib_term = 1;
  let mut next_fib_term = 2;
  let mut list = Vec::new();

  while next_fib_term < LIMIT {
    if next_fib_term % 2 == 0 {
      list.push(next_fib_term);
    }

    let new_next_fib_term = next_fib_term + previous_fib_term;
    previous_fib_term = next_fib_term;
    next_fib_term = new_next_fib_term;
  }

  return list.iter().sum();
}