import chalk from 'chalk';
import multiplesof3and5 from './1_multipleof3and5';
import evenfibonaccinumbers from './2_evenfibonaccinumbers';

function outputProblem(title, description, problem) {
  console.log(chalk.yellow.underline(''));
  console.log(chalk.yellow(description));
  console.log(problem());
}

outputProblem(
  '1. Multiple of 3 and 5:',
  'If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\nFind the sum of all the multiples of 3 or 5 below 1000.',
  multiplesof3and5
);

outputProblem(
  '2. Even Fibonacci numbers:',
  'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.',
  evenfibonaccinumbers
);
